config/routes.rb
Masterthought::Application.routes.draw do

  resources :articles
  match '/feed' => 'feeds#articles',
        :as => :feed,
        :defaults => {:format => 'atom'}

  match "/search" => "master#search", :as => :search

  match "/section/:id" => "master#section", :as => :section
  match "/section/:id/article/:article" => "master#section", :as => :section_article

  match "/signout" => "services#signout"

  match '/auth/:service/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  match "/admin" => "admin#index", :as => :admin_index
  match "/login" => "admin#login", :as => :admin_signin

  match "/comments/create" => "comments#create", :as => :create_comment

  namespace :admin do
    match "/articles/new" => "articles#new", :as => :new_article
    match "/articles/create" => "articles#create", :as => :create_article
    match "/articles/edit/:id" => "articles#edit", :as => :edit_article
    match "/articles/update/:id" => "articles#update", :as => :update_article
    match "/articles/delete/:id" => "articles#delete", :as => :delete_article

    match "/uploads/new" => "uploads#new", :as => :new_upload
    match "/uploads/create" => "uploads#create", :as => :create_upload
    match "/uploads/delete/:id" => "uploads#delete", :as => :delete_upload
    match "/uploads/edit/:id" => "uploads#edit", :as => :edit_upload
    match "/uploads/update/:id" => "uploads#update", :as => :update_upload

    match "/sections/new" => "sections#new", :as => :new_section
    match "/sections/create" => "sections#create", :as => :create_section
    match "/sections/edit/:id" => "sections#edit", :as => :edit_section
    match "/sections/update/:id" => "sections#update", :as => :update_section
    match "/sections/delete/:id" => "sections#delete", :as => :delete_section

    match "/snippets/new" => "snippets#new", :as => :new_snippet
    match "/snippets/create" => "snippets#create", :as => :create_snippet
    match "/snippets/edit/:id" => "snippets#edit", :as => :edit_snippet
    match "/snippets/update/:id" => "snippets#update", :as => :update_snippet
    match "/snippets/delete/:id" => "snippets#delete", :as => :delete_snippet

    match "/comments/edit/:id" => "comments#edit", :as => :edit_comment
    match "/comments/update/:id" => "comments#update", :as => :update_comment
    match "/comments/delete/:id" => "comments#delete", :as => :delete_comment

    match "/users/show" => "users#show", :as => :show_users
    match "/users/edit/:id" => "users#edit", :as => :edit_user
    match "/users/update/:id" => "users#update", :as => :update_user
    match "/users/delete/:id" => "users#delete", :as => :delete_user

    match "/settings/new" => "settings#new", :as => :new_setting
    match "/settings/create" => "settings#create", :as => :create_setting
    match "/settings/update_key/:id" => "settings#update_key", :as => :update_key_setting
    match "/settings/update_value/:id" => "settings#update_value", :as => :update_value_setting
    match "/settings/delete/:id" => "settings#delete", :as => :delete_setting

    resources :Jqueryfiletree
      match "/extend/content" => "extend#content", :as => :show_tree
      match "/extend/new" => "extend#new", :as => :new_extend

    match "/extend/create" => "extend#create", :as => :create_extend
    match "/extend/update" => "extend#update", :as => :update_extend
    match "/extend/edit/filename/:filename/filepath/:filepath" => "extend#edit", :as => :edit_extend
    match "/extend/delete/filename/:filename/filepath/:filepath" => "extend#delete", :as => :delete_extend

  end

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end

  resources :users, :only => [:index] do
    collection do
      get 'test'
    end
  end

  root :to => 'master#section'

end

app/views/admin/index.html.erb
<div class="grid_5" style="padding-bottom:20px;">
  <%= link_to "New Article", admin_new_article_path, :class => "button orange", :style => "color:black;", :id => "new_article" %>
  <%= link_to "New Section", admin_new_section_path, :class => "button blue", :style => "color:black;" %>
  <%= link_to "Upload Asset", admin_new_upload_path, :class => "button purple", :style => "color:black;" %>
</div>

<div class="box grid_12">
  <div class="box-head"><h2>Articles</h2></div>
  <div class="box-content no-pad">
    <table class="display" id="articles">
      <thead>
      <tr>
        <th>Article</th>
        <th>Section</th>
        <th>Tags</th>
        <th>Comments</th>
        <th>Published</th>
        <th>Author</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @articles.sort_by { |x| x.id }.reverse.each_with_index do |article, i| %>
          <tr class="<%= (i%2 == 0) ? "even" : "odd" %>">
            <td><span id="<%= i %>_title"><%= article.title %></span></td>
            <td align="center"><span id="<%= i %>_tags"><%= article.section.name %></span></td>
            <td align="center"><span id="<%= i %>_tags"><%= article.tags %></span></td>
            <td align="center"><span id="<%= i %>_comments"><%= article.comments.size %></span></td>
            <td align="center"><span id="<%= i %>_time"><%= article.created_at.strftime("%x %X") %></span></td>
            <td align="center"><span id="<%= i %>_name"><%= article.user.name %></span></td>
            <td align="center"><%= link_to image_tag('cross.png'), admin_delete_article_path(article.id), :style => "padding-right:20px;", :class => "confirm", :title => "Are you sure you want to delete this Article?" %>  <%= link_to image_tag('pencil.png'), admin_edit_article_path(article.id) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="box grid_12">
  <div class="box-head"><h2>Comments</h2></div>
  <div class="box-content no-pad">
    <table class="display" id="comments">
      <thead>
      <tr>
        <th>Name</th>
        <th>Article</th>
        <th>Comment</th>
        <th>Published</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% Comment.all.sort_by { |x| x.id }.reverse.each_with_index do |comment, i| %>
          <tr class="<%= (i%2 == 0) ? "even" : "odd" %>">
            <td><span id="<%= i %>_name"><%= comment.name %></span></td>
            <td align="center"><span id="<%= i %>_title"><%= comment.article.title %></span></td>
            <td align="center"><span id="<%= i %>_content"><%= comment.content %></span></td>
            <td align="center"><span id="<%= i %>_time"><%= comment.created_at.strftime("%x %X") %></span></td>
            <td align="center"><%= link_to image_tag('cross.png'), admin_delete_comment_path(comment.id), :style => "padding-right:20px;", :class => "confirm", :title => "Are you sure you want to delete this Comment?" %>  <%= link_to image_tag('pencil.png'), admin_edit_comment_path(comment.id) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
    $('#articles').dataTable({
        "bJQueryUI":true,
        "sPaginationType":"full_numbers"
    });

    $('#comments').dataTable({
        "bJQueryUI":true,
        "sPaginationType":"full_numbers"
    });
</script>

app/views/admin/login.html.erb
<h1>Login to blog Admin</h1>

<div>
  <ul>
    <span>Sign in with:</span>
    <li><%= link_to "Facebook", "/auth/facebook" %></li>
  </ul>
</div>