config/routes.rb
Masterthought::Application.routes.draw do

  resources :articles
  match '/feed' => 'feeds#articles',
        :as => :feed,
        :defaults => {:format => 'atom'}

  match "/search" => "master#search", :as => :search

  match "/section/:id" => "master#section", :as => :section
  match "/section/:id/article/:article" => "master#section", :as => :section_article

  match "/signout" => "services#signout"

  match '/auth/:service/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  match "/admin" => "admin#index", :as => :admin_index
  match "/login" => "admin#login", :as => :admin_signin

  match "/comments/create" => "comments#create", :as => :create_comment

  namespace :admin do
    match "/articles/new" => "articles#new", :as => :new_article
    match "/articles/create" => "articles#create", :as => :create_article
    match "/articles/edit/:id" => "articles#edit", :as => :edit_article
    match "/articles/update/:id" => "articles#update", :as => :update_article
    match "/articles/delete/:id" => "articles#delete", :as => :delete_article

    match "/uploads/new" => "uploads#new", :as => :new_upload
    match "/uploads/create" => "uploads#create", :as => :create_upload
    match "/uploads/delete/:id" => "uploads#delete", :as => :delete_upload
    match "/uploads/edit/:id" => "uploads#edit", :as => :edit_upload
    match "/uploads/update/:id" => "uploads#update", :as => :update_upload

    match "/sections/new" => "sections#new", :as => :new_section
    match "/sections/create" => "sections#create", :as => :create_section
    match "/sections/edit/:id" => "sections#edit", :as => :edit_section
    match "/sections/update/:id" => "sections#update", :as => :update_section
    match "/sections/delete/:id" => "sections#delete", :as => :delete_section

    match "/snippets/new" => "snippets#new", :as => :new_snippet
    match "/snippets/create" => "snippets#create", :as => :create_snippet
    match "/snippets/edit/:id" => "snippets#edit", :as => :edit_snippet
    match "/snippets/update/:id" => "snippets#update", :as => :update_snippet
    match "/snippets/delete/:id" => "snippets#delete", :as => :delete_snippet

    match "/comments/edit/:id" => "comments#edit", :as => :edit_comment
    match "/comments/update/:id" => "comments#update", :as => :update_comment
    match "/comments/delete/:id" => "comments#delete", :as => :delete_comment

    match "/users/show" => "users#show", :as => :show_users
    match "/users/edit/:id" => "users#edit", :as => :edit_user
    match "/users/update/:id" => "users#update", :as => :update_user
    match "/users/delete/:id" => "users#delete", :as => :delete_user

    match "/settings/new" => "settings#new", :as => :new_setting
    match "/settings/create" => "settings#create", :as => :create_setting
    match "/settings/update_key/:id" => "settings#update_key", :as => :update_key_setting
    match "/settings/update_value/:id" => "settings#update_value", :as => :update_value_setting
    match "/settings/delete/:id" => "settings#delete", :as => :delete_setting

    resources :Jqueryfiletree
      match "/extend/content" => "extend#content", :as => :show_tree
      match "/extend/new" => "extend#new", :as => :new_extend

    match "/extend/create" => "extend#create", :as => :create_extend
    match "/extend/update" => "extend#update", :as => :update_extend
    match "/extend/edit/filename/:filename/filepath/:filepath" => "extend#edit", :as => :edit_extend
    match "/extend/delete/filename/:filename/filepath/:filepath" => "extend#delete", :as => :delete_extend

  end

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end

  resources :users, :only => [:index] do
    collection do
      get 'test'
    end
  end

  root :to => 'master#section'

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :key, :value

  validates :key, :presence => true
  validates :value, :presence => true

  def self.get(key)
    setting = Setting.find_by_key(key)
    setting.value unless setting.nil?
  end

  def self.get?(key)
    setting = Setting.find_by_key(key)
    if !setting.nil?
      key = setting.value
      key == "true"
    end
  end

end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  before_filter :authenticate_user!
  protect_from_forgery :except => [:update_key, :update_value]
  layout 'admin_layout'

  def new
    @settings = Setting.all
    @setting = Setting.new
  end

  def create
    @settings = Setting.all
    @setting = Setting.new(params[:setting])
    if @setting.save
      redirect_to admin_new_setting_path
    else
      render admin_new_setting_path
    end
  end

  def update_key
    value = params[:value]
    setting = Setting.find_by_id(params[:id])
    setting.key = params[:value]
    setting.save
    render :text => setting.key
  end

  def update_value
    value = params[:value]
    setting = Setting.find_by_id(params[:id])
    setting.value = params[:value]
    setting.save
    render :text => setting.value
  end

  #def update
  #  @settings = Setting.all
  #  @setting = Setting.new(params[:setting])
  #  if @setting.update_attributes(params[:setting])
  #    redirect_to admin_new_setting_path
  #  else
  #    render admin_edit_setting_path
  #  end
  #end

  def delete
    Setting.find(params[:id]).destroy
    redirect_to admin_new_setting_path
  end
end

app/views/admin/settings/new.html.erb
<div class="box grid_7">
  <div class="box-head"><h2>Create New Setting</h2></div>
  <div class="box-content">
    <%= form_for @setting, :as => :setting, :url => admin_create_setting_url, :html => {:class => 'block-content form'} do |f| %>

        <div class="form-row">
          <p class="form-label">Key:</p>

          <div class="form-item"><%= f.text_field :key %></div>
        </div>

        <div class="form-row">
          <p class="form-label">Value:</p>

          <div class="form-item"><%= f.text_field :value %></div>
        </div>

        <div style="float:right;">
          <input type="submit" class="button yellow" value="Create Setting">
        </div>

    <% end %>
    <div class="clear"></div>
  </div>
</div>

<div class="grid_7">
  <% @setting.errors.full_messages.each do |msg| %>
      <div class="ad-notif-error"><p><%= msg %></p></div>
  <% end %>
</div>

<div class="box grid_7">
  <div class="box-head"><h2>Settings</h2></div>
  <div class="box-content no-pad">
    <table class="display" id="dt5">
      <thead>
      <tr>
        <th>Key</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @settings.sort_by { |x| x.created_at }.reverse.each do |setting| %>
          <tr>
            <td><span id="settings-admin-edit-key-<%= setting.id %>"><%= setting.key %></span></td>
            <td><span id="settings-admin-edit-value-<%= setting.id %>"><%= setting.value %></span></td>
            <td align="center"><%= link_to image_tag('cross.png'), admin_delete_setting_path(setting.id), :style => "padding-right:20px;", :class => "confirm", :title => "Are you sure you want to delete this Setting?" %> </td>
            <script>
                $('#settings-admin-edit-key-<%= setting.id%>').editable('<%= admin_update_key_setting_path(setting.id)%>', {
                    submit:'OK'
                });
                $('#settings-admin-edit-value-<%= setting.id%>').editable('<%= admin_update_value_setting_path(setting.id)%>', {
                    submit:'OK'
                });
            </script>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
    $('#dt5').dataTable({
        "bJQueryUI":true,
        "sPaginationType":"full_numbers"
    });
</script>