config/routes.rb
Masterthought::Application.routes.draw do

  resources :articles
  match '/feed' => 'feeds#articles',
        :as => :feed,
        :defaults => {:format => 'atom'}

  match "/search" => "master#search", :as => :search

  match "/section/:id" => "master#section", :as => :section
  match "/section/:id/article/:article" => "master#section", :as => :section_article

  match "/signout" => "services#signout"

  match '/auth/:service/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  match "/admin" => "admin#index", :as => :admin_index
  match "/login" => "admin#login", :as => :admin_signin

  match "/comments/create" => "comments#create", :as => :create_comment

  namespace :admin do
    match "/articles/new" => "articles#new", :as => :new_article
    match "/articles/create" => "articles#create", :as => :create_article
    match "/articles/edit/:id" => "articles#edit", :as => :edit_article
    match "/articles/update/:id" => "articles#update", :as => :update_article
    match "/articles/delete/:id" => "articles#delete", :as => :delete_article

    match "/uploads/new" => "uploads#new", :as => :new_upload
    match "/uploads/create" => "uploads#create", :as => :create_upload
    match "/uploads/delete/:id" => "uploads#delete", :as => :delete_upload
    match "/uploads/edit/:id" => "uploads#edit", :as => :edit_upload
    match "/uploads/update/:id" => "uploads#update", :as => :update_upload

    match "/sections/new" => "sections#new", :as => :new_section
    match "/sections/create" => "sections#create", :as => :create_section
    match "/sections/edit/:id" => "sections#edit", :as => :edit_section
    match "/sections/update/:id" => "sections#update", :as => :update_section
    match "/sections/delete/:id" => "sections#delete", :as => :delete_section

    match "/snippets/new" => "snippets#new", :as => :new_snippet
    match "/snippets/create" => "snippets#create", :as => :create_snippet
    match "/snippets/edit/:id" => "snippets#edit", :as => :edit_snippet
    match "/snippets/update/:id" => "snippets#update", :as => :update_snippet
    match "/snippets/delete/:id" => "snippets#delete", :as => :delete_snippet

    match "/comments/edit/:id" => "comments#edit", :as => :edit_comment
    match "/comments/update/:id" => "comments#update", :as => :update_comment
    match "/comments/delete/:id" => "comments#delete", :as => :delete_comment

    match "/users/show" => "users#show", :as => :show_users
    match "/users/edit/:id" => "users#edit", :as => :edit_user
    match "/users/update/:id" => "users#update", :as => :update_user
    match "/users/delete/:id" => "users#delete", :as => :delete_user

    match "/settings/new" => "settings#new", :as => :new_setting
    match "/settings/create" => "settings#create", :as => :create_setting
    match "/settings/update_key/:id" => "settings#update_key", :as => :update_key_setting
    match "/settings/update_value/:id" => "settings#update_value", :as => :update_value_setting
    match "/settings/delete/:id" => "settings#delete", :as => :delete_setting

    resources :Jqueryfiletree
      match "/extend/content" => "extend#content", :as => :show_tree
      match "/extend/new" => "extend#new", :as => :new_extend

    match "/extend/create" => "extend#create", :as => :create_extend
    match "/extend/update" => "extend#update", :as => :update_extend
    match "/extend/edit/filename/:filename/filepath/:filepath" => "extend#edit", :as => :edit_extend
    match "/extend/delete/filename/:filename/filepath/:filepath" => "extend#delete", :as => :delete_extend

  end

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end

  resources :users, :only => [:index] do
    collection do
      get 'test'
    end
  end

  root :to => 'master#section'

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  attr_accessible :name, :content

  validates :name, :presence => true
  validates :content, :presence => true

end

app/controllers/admin/snippets_controller.rb
class Admin::SnippetsController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin_layout'

  def new
    @uploads = Upload.all
    @snippets = Snippet.all
    @snippet = Snippet.new
  end

  def create
    @uploads = Upload.all
    @snippets = Snippet.all
    @snippet = Snippet.new(params[:snippet])
    if @snippet.save
      redirect_to admin_new_snippet_path
    else
      render admin_new_snippet_path
    end
  end

  def update
    @uploads = Upload.all
    @snippets = Snippet.all
    @snippet = Snippet.find(params[:id])
    if @snippet.update_attributes(params[:snippet])
      redirect_to admin_edit_snippet_path(@snippet.id)
    else
      render admin_edit_snippet_path(@snippet.id)
    end
  end

  def edit
    @uploads = Upload.all
    @snippets = Snippet.all
    @snippet = Snippet.find(params[:id])
  end

  def delete
    Snippet.find(params[:id]).destroy
    redirect_to admin_new_snippet_path
  end
end

app/views/admin/snippets/_snippet_boxes.html.erb
<div class="grid_10">
  <% @snippet.errors.full_messages.each do |msg| %>
      <div class="ad-notif-error"><p><%= msg %></p></div>
  <% end %>
</div>


<div class="box grid_5">
  <div class="box-head"><h2>Snippets</h2></div>
  <div class="box-content no-pad">
    <table class="display" id="dt3">
      <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @snippets.sort_by { |x| x.created_at }.reverse.each do |snippet| %>
          <tr>
            <td><%= snippet.name %></td>
            <td align="center"><%= link_to image_tag('cross.png'), admin_delete_snippet_path(snippet.id), :style => "padding-right:20px;", :class => "confirm", :title => "Are you sure you want to delete this Section?" %>  <%= link_to image_tag('pencil.png'), admin_edit_snippet_path(snippet.id) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="box grid_5">
  <div class="box-head"><h2>Uploads</h2></div>
  <div class="box-content no-pad">
    <table class="display" id="dt4">
      <thead>
      <tr>
        <th>Upload</th>
        <th>Type</th>
        <th>Path</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>

      <script>
          ZeroClipboard.setMoviePath('/assets/zeroclipboard/ZeroClipboard.swf');
      </script>

      <% @uploads.sort_by { |x| x.created_at }.reverse.each_with_index do |upload, i| %>
          <tr>
            <td align="center">
              <% if upload.is_image? %>
                  <%= link_to((image_tag upload.upload.url(:thumb), :style => "border: 1px solid black;"), upload.upload.url(:large), {:id => "upload_#{i}"}) %>
              <% else %>
                  <%= link_to(image_tag('mime/text.png', :height => 48, :width => 48), upload.upload.url, {:id => "upload_#{i}"}) %>
              <% end %>
            </td>
            <td align="center"><%= upload.upload_content_type %></td>
            <td align="center"><%= upload.file_name %></td>
            <td align="center">

              <div id="d_clip_container_<%= i %>" style="position:relative">
                <button type="button" id="d_clip_button_<%= i %>" class="button purple">Copy</button>

              </div>

              <script>
                  function copyText_<%= i %>(event) {
                      var clip_<%= i %> = new ZeroClipboard.Client();
                      clip_<%= i %>.setText('<%= upload.upload.url(:original).split('?')[0]%>');
                      clip_<%= i %>.glue('d_clip_button_<%= i %>', 'd_clip_container_<%= i %>');
                  }

                  $('#d_clip_button_<%= i %>').mouseover(copyText_<%= i%>);
              </script>

            </td>
          </tr>
      <% end %>
      </tbody>
    </table>


    <div class="clear"></div>
  </div>
</div>

<script>
    var editor = CodeMirror.fromTextArea(document.getElementsByClassName("markdown-content")[0], {
        mode:'markdown',
        matchBrackets:true,
        lineNumbers:true,
        theme:'eclipse',
        onCursorActivity:function () {
            editor.matchHighlight("CodeMirror-matchhighlight");
        },
        extraKeys:{
            "'>'":function (cm) {
                cm.closeTag(cm, '>');
            },
            "'/'":function (cm) {
                cm.closeTag(cm, '/');
            }
        }

    });



    function getSelectedRange() {
        return { from:editor.getCursor(true), to:editor.getCursor(false) };
    }

    function autoFormatSelection() {
        CodeMirror.commands["selectAll"](editor);
        var range = getSelectedRange();
        editor.autoFormatRange(range.from, range.to);
    }

    function commentSelection(isComment) {
        var range = getSelectedRange();
        editor.commentRange(isComment, range.from, range.to);
    }


    $('#dt3').dataTable({
        "bJQueryUI":true,
        "sPaginationType":"full_numbers"
    });

    $('#dt4').dataTable({
        "bJQueryUI":true,
        "sPaginationType":"full_numbers"
    });

</script>

app/views/admin/snippets/edit.html.erb
<div class="box grid_10">
  <div class="box-head"><h2>Edit Snippet</h2></div>
  <div class="box-content">
    <%= form_for @snippet, :as => :snippet, :url => admin_update_snippet_url, :html => {:class => 'block-content form'} do |f| %>

        <div class="form-row">
          <p class="form-label">Name:</p>

          <div class="form-item"><%= f.text_field :name %></div>
        </div>

        <div class="form-row">
          <p class="form-label">Content:</p>

          <div class="form-item"><%= f.text_area :content, :class => "markdown-content" %></div>
        </div>

        <div style="float:right;">
          <%= render :partial => 'admin/shared/formatting_links', :locals => {:selection => @snippet } %>
          <input type="submit" class="button yellow" value="Update Snippet">
        </div>

    <% end %>
    <div class="clear"></div>
  </div>
</div>

<%= render :partial => 'admin/snippets/snippet_boxes' %>

app/views/admin/snippets/new.html.erb
<div class="box grid_10">
  <div class="box-head"><h2>Create New Snippet</h2></div>
  <div class="box-content">
    <%= form_for @snippet, :as => :snippet, :url => admin_create_snippet_url, :html => {:class => 'block-content form'} do |f| %>

        <div class="form-row">
          <p class="form-label">Name:</p>

          <div class="form-item"><%= f.text_field :name %></div>
        </div>

        <div class="form-row">
          <p class="form-label">Content:</p>

          <div class="form-item"><%= f.text_area :content, :class => "markdown-content" %></div>
        </div>

        <div style="float:right;">
          <%= render :partial => 'admin/shared/formatting_links', :locals => {:selection => @snippet } %>
          <input type="submit" class="button yellow" value="Create Snippet">
        </div>

    <% end %>
    <div class="clear"></div>
  </div>
</div>

<%= render :partial => 'admin/snippets/snippet_boxes' %>